-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 05:13:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema caninos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema caninos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caninos` DEFAULT CHARACTER SET utf8 ;
USE `caninos` ;

-- -----------------------------------------------------
-- Table `caninos`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caninos`.`agenda` (
  `id_agenda` INT NOT NULL,
  `id_cliente` INT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`id_agenda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caninos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caninos`.`cliente` (
  `id_cliente` INT NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `celular_cliente` VARCHAR(45) NOT NULL,
  `domicilio_cliente` VARCHAR(45) NULL,
  `correo_cliente` VARCHAR(45) NULL,
  `id_agenda` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_agenda1_idx` (`id_agenda` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_agenda1`
    FOREIGN KEY (`id_agenda`)
    REFERENCES `caninos`.`agenda` (`id_agenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caninos`.`control_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caninos`.`control_servicios` (
  `id_cita` INT NOT NULL,
  `fecha` DATE NULL,
  `servicio_iniciado` VARCHAR(45) NULL,
  `servicio_finalizado` VARCHAR(45) NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`id_cita`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caninos`.`facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caninos`.`facturacion` (
  `id_facturacion` INT NOT NULL,
  `id_cita` INT NULL,
  `fecha_servicio` DATE NOT NULL,
  `tipo_servicio` VARCHAR(45) NOT NULL,
  `valor_servicio` INT NOT NULL,
  PRIMARY KEY (`id_facturacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `caninos`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `caninos`.`cita` (
  `id_cita` INT NOT NULL AUTO_INCREMENT,
  `nombre_perro` VARCHAR(45) NOT NULL,
  `raza_perro` VARCHAR(45) NOT NULL,
  `tamanio_perro` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_cliente` INT NOT NULL,
  `control_servicios_id_cita` INT NOT NULL,
  `facturacion_id_facturacion` INT NOT NULL,
  PRIMARY KEY (`id_cita`),
  INDEX `fk_cita_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_cita_control_servicios1_idx` (`control_servicios_id_cita` ASC) VISIBLE,
  INDEX `fk_cita_facturacion1_idx` (`facturacion_id_facturacion` ASC) VISIBLE,
  CONSTRAINT `fk_cita_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `caninos`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_control_servicios1`
    FOREIGN KEY (`control_servicios_id_cita`)
    REFERENCES `caninos`.`control_servicios` (`id_cita`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_facturacion1`
    FOREIGN KEY (`facturacion_id_facturacion`)
    REFERENCES `caninos`.`facturacion` (`id_facturacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
